### ISSUE TITLE
How to compile under Linux

### ISSUE THREAD

**Issue by mitjafelicijan** [osen/openradiant#4]
Can you provide information how to compile this under Linux?

**Comment by osen** [comment]
Hi there,

Currently only Windows and OpenBSD are supported. A couple of Linux distros are on my TODO list but we don't really have the build infrastructure in place yet for it (or macOS).

So it is missing a few bits before it will build (the virtual filesystem and lightmap baker). Other than that, it is a fairly typical CMake setup. i.e:

    mkdir build
    cd build
    cmake ..
    cd ..
    cmake --build build

I will keep this issue open until Linux support is in there.

**Comment by ghost** [comment]
What needs to be done for the GNU/Linux compilation? Maybe I or someone else can help if you provide as much detail as possible on what needs to be done.

**Comment by stefano-elysium** [comment]
+1
