### ISSUE TITLE
Flagged as a virus

### ISSUE THREAD

**Issue by TechnikEmpire** [osen/openradiant#5]
Windows build is being flagged as a virus, quite a nasty one at that.

https://www.virustotal.com/gui/file/7d41750f3d6bc3bbb6144a3e61ad5c1f6c9a99ef70cb686ddc2cd7621811ac72/detection

**Comment by osen** [comment]
Oh nasty.

Probably to do with how I packed it (i.e so it is all in a single .exe). If you are worried, perhaps extract the .exe with 7zip and run the individual files through the checks.

Closing this issue because there isn't really anything that needs to be done this end.
